[package]
name = "rusted_minecraft"
version = "0.0.0"
authors = ["Cruz Julian Bishop <cruzjbishop@gmail.com>"]
description = "A Minecraft server programmed in Rust"

repository = "https://github.com/Techern/RustedMinecraft"
readme = "README.md"
keywords = ["Minecraft", "Server"]
license = "MIT"

[dependencies]
semver = "0.1.20"
log = "0.3.1"
